name: Typecheck and Linting 

on: [push, pull_request]

env: 
  DATABASE_URL: "https://fake.com"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: npm install

    - name: TypeScript Type Check
      run: npm run typecheck

    - name: Lint
      run: npm run lint
